import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import sharp from "sharp";
import { beforeAll, beforeEach, describe, expect, it } from "vitest";
import { PUT as putUpload } from "@/app/api/v1/uploads/[uploadId]/route";
import { assetDir } from "../assets";
import { openDatabase, setDbForTests } from "../db";
import type { Actor } from "../http";
import { listActivity } from "./activity";
import { addSpread, cloneBookSetup, createBook, deleteBook, deleteSpread, getBook, restoreActivity } from "./books";
import { characterReferences, createCharacter, getCharacter, listCharacters } from "./characters";
import { createSeries, getSeries, updateSeries } from "./series";
import { commitUpload, commitUploads, createCharacterWithUploads, createUploads, receiveUpload, setCoverFromUpload } from "./uploads";

const human: Actor = { type: "human", name: "Guillaume", scope: "owner" };
const agent: Actor = { type: "agent", name: "Claude", scope: "write" };
const ORIGIN = "https://lafabrique.test";

let big: Buffer; // ~3 MB PNG, like an image generated by Gemini
let small: Buffer;

beforeAll(async () => {
  // Noise does not compress: 1024 × 1024 × 3 bytes ≈ 3 MB of PNG.
  big = await sharp(crypto.randomBytes(1024 * 1024 * 3), { raw: { width: 1024, height: 1024, channels: 3 } }).png({ compressionLevel: 1 }).toBuffer();
  small = await sharp({ create: { width: 300, height: 200, channels: 3, background: "#d2691e" } }).jpeg().toBuffer();
});

beforeEach(() => {
  process.env.DATA_DIR = fs.mkdtempSync(path.join(os.tmpdir(), "lafabrique-"));
  setDbForTests(openDatabase(":memory:"));
});

function token(url: string): string {
  return new URL(url).searchParams.get("token") as string;
}

/** create_upload → curl -T → (commit): the flow of an agent with local files. */
async function send(ticket: { uploadId: string; uploadUrl: string }, file: Buffer) {
  return receiveUpload(ticket.uploadId, token(ticket.uploadUrl), async () => file);
}

describe("direct uploads", () => {
  it("attaches a 3 MB file to each target, attributed to the agent", async () => {
    expect(big.length).toBeGreaterThan(3_000_000);
    const book = createBook({ title: "Victoire", spreadCount: 2 }, human);
    const mama = createCharacter({ bookId: book.id }, { name: "Mama" }, human);
    const { uploads } = createUploads(
      {
        bookId: book.id,
        files: [
          { kind: "spread_illustration", targetId: book.spreads[0]!.id, filename: "p1.png" },
          { kind: "cover", filename: "couverture.png" },
          { kind: "character_image", targetId: mama.id, filename: "mama-dos.png", label: "dos" },
          { kind: "image", filename: "constance-face.png" },
        ],
      },
      agent,
      ORIGIN,
    );
    expect(uploads).toHaveLength(4);
    expect(uploads[0]!.uploadUrl).toMatch(/^https:\/\/lafabrique\.test\/api\/v1\/uploads\/\w+\?token=/);
    expect(uploads[0]!.curl).toContain("curl -sS --fail-with-body -T 'p1.png'");
    for (const u of uploads) expect((await send(u, big)).status).toBe("received");

    const { results } = commitUploads(uploads.map((u) => u.uploadId));
    expect(results.map((r) => ("status" in r ? r.status : r.error))).toEqual(["attached", "attached", "attached", "ready"]);
    const illustration = results[0] as Extract<(typeof results)[number], { status: string }>;
    expect(illustration.asset).toMatchObject({ width: 1024, height: 1024, format: "png" });
    expect(illustration.dpi).toBe(126);
    expect(illustration.warnings.map((w) => w.code)).toEqual(["lowResolution"]);

    const after = getBook(book.id);
    expect(after.spreads[0]?.illustration?.width).toBe(1024);
    expect(after.spreads[0]?.updatedBy).toEqual({ type: "agent", name: "Claude" });
    expect(after.cover?.id).toBe((results[1] as { asset: { id: string } }).asset.id);
    const image = getCharacter(mama.id).images[0]!;
    expect([image.label, image.view, image.createdBy.type]).toEqual(["dos", "back", "agent"]);

    // A free image becomes a new character's reference, once.
    const constance = createCharacterWithUploads({ bookId: book.id }, { name: "Constance", images: [{ uploadId: uploads[3]!.uploadId, label: "face" }] }, agent);
    expect(constance.images.map((i) => [i.view, i.primary, i.image.width])).toEqual([["front", true, 1024]]);
    expect(() => setCoverFromUpload(book.id, uploads[3]!.uploadId, agent)).toThrow(/déjà utilisé/);
  });

  it("keeps a small image with a warning, never refuses it", async () => {
    const book = createBook({ title: "Victoire", spreadCount: 1 }, human);
    const [ticket] = createUploads({ bookId: book.id, kind: "spread_illustration", targetId: book.spreads[0]!.id, filename: "mini.jpg", autoCommit: true }, agent, ORIGIN).uploads;
    const result = await send(ticket!, small);
    expect(result.status).toBe("attached");
    expect(result.dpi).toBeLessThan(50);
    expect(result.warnings.map((w) => w.code)).toEqual(["lowResolution", "aspectRatio"]);
    expect(getBook(book.id).spreads[0]?.illustration?.width).toBe(300);
  });

  it("is single-use, signed and short-lived", async () => {
    const book = createBook({ title: "Victoire", spreadCount: 0 }, human);
    const [ticket] = createUploads({ bookId: book.id, kind: "cover", filename: "c.png" }, agent, ORIGIN).uploads;
    await expect(receiveUpload(ticket!.uploadId, "forged", async () => small)).rejects.toMatchObject({ status: 403 });
    await expect(receiveUpload(ticket!.uploadId, token(ticket!.uploadUrl), async () => Buffer.from("not an image"))).rejects.toMatchObject({ status: 400 });
    // A failed transfer leaves the link usable…
    await send(ticket!, small);
    // …a received one does not.
    await expect(send(ticket!, small)).rejects.toMatchObject({ status: 409 });
    expect(commitUpload(ticket!.uploadId)).toEqual(commitUpload(ticket!.uploadId));

    const [late] = createUploads({ bookId: book.id, kind: "cover", filename: "late.png" }, agent, ORIGIN).uploads;
    const { getDb } = await import("../db");
    getDb().prepare("UPDATE uploads SET expires_at = ? WHERE id = ?").run(new Date(Date.now() - 1000).toISOString(), late!.uploadId);
    await expect(send(late!, small)).rejects.toMatchObject({ status: 410 });
    expect(() => commitUpload(late!.uploadId)).toThrow(/pas encore reçu/);
  });

  it("receives a raw PUT on the signed URL (curl -T) without a key", async () => {
    const book = createBook({ title: "Victoire", spreadCount: 1 }, human);
    const [ticket] = createUploads({ bookId: book.id, kind: "spread_illustration", targetId: book.spreads[0]!.id, filename: "p1.png" }, agent, ORIGIN).uploads;
    const url = ticket!.uploadUrl.replace(ORIGIN, "http://localhost");
    const res = await putUpload(new Request(url, { method: "PUT", body: new Uint8Array(big), headers: { "content-length": String(big.length) } }), {
      params: Promise.resolve({ uploadId: ticket!.uploadId }),
    });
    expect(res.status).toBe(200);
    expect(await res.json()).toMatchObject({ uploadId: ticket!.uploadId, status: "received", asset: { width: 1024 } });
    const again = await putUpload(new Request(url, { method: "PUT", body: new Uint8Array(small) }), { params: Promise.resolve({ uploadId: ticket!.uploadId }) });
    expect(again.status).toBe(409);
  });

  it("records which image went where, and every image change is undoable", async () => {
    const book = createBook({ title: "Victoire", spreadCount: 1 }, human);
    const spread = book.spreads[0]!;
    for (const name of ["v1.png", "v2.png"]) {
      const [t] = createUploads({ bookId: book.id, kind: "spread_illustration", targetId: spread.id, filename: name, autoCommit: true }, agent, ORIGIN).uploads;
      await send(t!, name === "v1.png" ? small : big);
    }
    const entries = listActivity({ bookId: book.id }, { spreadId: spread.id }).filter((e) => e.details.length > 0);
    expect(entries.map((e) => e.details[0]?.filename)).toEqual(["v2.png", "v1.png"]);
    expect(entries[0]?.details[0]).toMatchObject({ target: "spread_illustration", targetId: spread.id, width: 1024, dpi: 126 });
    expect(entries[0]?.actor).toEqual({ type: "agent", name: "Claude" });
    restoreActivity(entries[0]!.id, human);
    expect(getBook(book.id).spreads[0]?.illustration?.width).toBe(300);
  });
});

describe("spreads", () => {
  it("renumbers pages when one is added or deleted", () => {
    const book = createBook({ title: "Victoire", spreadCount: 3 }, human);
    const [a, b, c] = book.spreads.map((s) => s.id);
    const inserted = addSpread(book.id, { position: 1 }, agent);
    expect(getBook(book.id).spreads.map((s) => [s.id, s.position])).toEqual([
      [a, 0],
      [inserted.id, 1],
      [b, 2],
      [c, 3],
    ]);
    deleteSpread(book.id, a!, agent);
    expect(getBook(book.id).spreads.map((s) => s.position)).toEqual([0, 1, 2]);
    expect(createBook({ title: "Vide", spreadCount: 0 }, human).spreads).toHaveLength(0);
  });
});

describe("series", () => {
  it("turns a model book into a series whose books share characters, style and rules", async () => {
    const model = createBook({ title: "Modèle", spreadCount: 0, format: "portrait-210x280", ageMin: 3, ageMax: 6, illustrationStyle: "aquarelle douce" }, human);
    const victoire = createCharacter({ bookId: model.id }, { name: "Victoire" }, human);
    const [t] = createUploads({ bookId: model.id, kind: "character_image", targetId: victoire.id, filename: "v.png", label: "profil gauche", autoCommit: true }, agent, ORIGIN).uploads;
    await send(t!, big);

    const { series, movedCharacters } = createSeries({ title: "Victoire et Constance", fromBookId: model.id, writingRules: "Toujours « Mama »." }, agent);
    expect(movedCharacters).toBe(1);
    expect(series.illustrationStyle).toBe("aquarelle douce");
    expect(series.characters[0]?.images[0]?.view).toBe("side_left");
    expect(getBook(model.id).seriesId).toBe(series.id);

    const tome2 = createBook({ title: "Tome 2", seriesId: series.id, spreadCount: 2, illustrationStyle: "hiver" }, agent);
    expect(tome2.format).toBe("portrait-210x280");
    expect([tome2.ageMin, tome2.ageMax]).toEqual([3, 6]);
    expect(tome2.characters.map((c) => c.id)).toEqual([victoire.id]);
    expect(tome2.effective.illustrationStyle).toBe("aquarelle douce\n\nhiver");
    expect(tome2.writingGuide).toContain("Toujours « Mama ».");

    // Linked, not copied: a change of the series shows in every book.
    updateSeries(series.id, { quoteStyle: "none", forbiddenWords: [{ word: "Maman", use: "Mama" }] }, human);
    expect(getBook(tome2.id).effective.quoteStyle).toBe("none");
    const refs = characterReferences({ bookId: tome2.id }, { origin: ORIGIN });
    expect(refs.illustrationStyle).toBe("aquarelle douce\n\nhiver");
    expect(refs.characters[0]?.byView).toEqual({ side_left: [refs.characters[0]!.images[0]!.id] });
    expect(getSeries(series.id).books.map((b) => b.title)).toEqual(["Modèle", "Tome 2"]);
  });

  it("clones a book's setup with copies of its own characters and images, without pages", async () => {
    const source = createBook({ title: "Source", spreadCount: 3, format: "square-250", writingRules: "Phrases courtes." }, human);
    const roux = createCharacter({ bookId: source.id }, { name: "Roux" }, human);
    const [t] = createUploads({ bookId: source.id, kind: "character_image", targetId: roux.id, filename: "roux.png", autoCommit: true }, agent, ORIGIN).uploads;
    await send(t!, small);
    const { book, copiedCharacters } = cloneBookSetup(source.id, { title: "Suite", spreadCount: 1 }, agent);
    expect(copiedCharacters).toBe(1);
    expect(book.format).toBe("square-250");
    expect(book.writingRules).toBe("Phrases courtes.");
    expect(book.spreads).toHaveLength(1);
    const copy = listCharacters(book.id)[0]!;
    expect(copy.id).not.toBe(roux.id);
    expect(copy.images[0]?.image.id).not.toBe(getCharacter(roux.id).images[0]?.image.id);
    // The copy owns its files: deleting the source keeps them.
    deleteBook(source.id, human);
    expect(fs.existsSync(assetDir(copy.images[0]!.image.id))).toBe(true);
    expect(getCharacter(copy.id).images).toHaveLength(1);
  });
});
