import { agentInstructions } from "@/server/agent-guide";
import { api, publicOrigin } from "@/server/http";

/** Self-description for agents: where things are and how to work. */
export const GET = api("read", ({ req }) => {
  const origin = publicOrigin(req);
  return {
    name: "La Fabrique",
    version: 1,
    mcp: `${origin}/api/mcp`,
    conventions: "REST : camelCase. MCP : snake_case, paramètres inconnus refusés.",
    endpoints: [
      "GET    /api/v1/me",
      "GET    /api/v1/formats",
      "GET    /api/v1/requests?to=agent",
      "GET    /api/v1/books?filter=all|active|done|archived&q=",
      "POST   /api/v1/books                          ({ title, spreadCount?, seriesId?, … })",
      "GET    /api/v1/books/{bookId}?summary=1&include=brief,rules,typography,spreads,characters",
      "PATCH  /api/v1/books/{bookId}",
      "POST   /api/v1/books/{bookId}/clone           ({ title, spreadCount?, includeBrief? } : same setup, no pages)",
      "GET    /api/v1/books/{bookId}/check-text?spreadId=&min=error|warning|info",
      "GET    /api/v1/books/{bookId}/contact-sheet?size=small|large   (image/jpeg)",
      "PUT    /api/v1/books/{bookId}/cover            (JSON {uploadId|base64|url} | multipart file | image/*)",
      "DELETE /api/v1/books/{bookId}/cover",
      "POST   /api/v1/books/{bookId}/spreads",
      "PUT    /api/v1/books/{bookId}/spreads           ({ order: [spreadId…] })",
      "GET    /api/v1/books/{bookId}/spreads/{spreadId}",
      "PATCH  /api/v1/books/{bookId}/spreads/{spreadId}",
      "DELETE /api/v1/books/{bookId}/spreads/{spreadId}",
      "PUT    /api/v1/books/{bookId}/spreads/{spreadId}/illustration   (JSON {uploadId|base64|url} | multipart file | image/*)",
      "DELETE /api/v1/books/{bookId}/spreads/{spreadId}/illustration",
      "GET    /api/v1/books/{bookId}/characters",
      "POST   /api/v1/books/{bookId}/characters      ({ name, role?, appearance?, position?, sourceCharacterId?, images?: [{ uploadId, label?, view?, primary? }] })",
      "PUT    /api/v1/books/{bookId}/characters      ({ order: [characterId…] })",
      "GET    /api/v1/characters/{characterId}",
      "PATCH  /api/v1/characters/{characterId}",
      "DELETE /api/v1/characters/{characterId}",
      "POST   /api/v1/characters/{characterId}/images            (JSON {uploadId|base64|url, label?, view?, primary?, position?} | multipart)",
      "PATCH  /api/v1/characters/{characterId}/images/{imageId}  ({ label?, view?, primary?, position? })",
      "DELETE /api/v1/characters/{characterId}/images/{imageId}",
      "GET    /api/v1/books/{bookId}/references?spreadId=&characterIds=&views=   (style + references + 24 h links)",
      "GET    /api/v1/series",
      "POST   /api/v1/series                          ({ title, fromBookId?, illustrationStyle?, writingRules?, quoteStyle?, forbiddenWords?, … })",
      "GET    /api/v1/series/{seriesId}",
      "PATCH  /api/v1/series/{seriesId}",
      "GET    /api/v1/series/{seriesId}/characters    (POST: create, PUT: order)",
      "GET    /api/v1/series/{seriesId}/references?characterIds=&views=",
      "GET    /api/v1/series/{seriesId}/activity",
      "POST   /api/v1/uploads                         ({ bookId|seriesId, kind, targetId?, filename, label?, view?, primary?, autoCommit?, files?: [...] })",
      "PUT    /api/v1/uploads/{uploadId}?token=       (no key: the file itself, curl -T ; POST multipart file also)",
      "POST   /api/v1/uploads/commit                  ({ uploadIds: [...] })",
      "GET    /api/v1/books/{bookId}/shares          (reading links; created and revoked by the human only)",
      "GET    /api/v1/books/{bookId}/comments?spreadId=&open=1",
      "POST   /api/v1/books/{bookId}/comments",
      "PATCH  /api/v1/comments/{commentId}             ({ resolved: boolean })",
      "GET    /api/v1/books/{bookId}/activity?spreadId=&characterId=",
      "POST   /api/v1/activity/{activityId}/restore?bookId=",
      "GET    /api/v1/books/{bookId}/events           (text/event-stream)",
      "GET    /api/v1/assets/{assetId}?size=original|print|web|thumb",
      "GET    /api/v1/fonts",
    ],
    guide: agentInstructions(origin),
  };
});
